### ISSUE TITLE
Code for: An End-to-End Neighborhood-based Interaction Model for Knowledge-enhanced Recommendation

### ISSUE THREAD

**Issue by marcromeyn** [Atomu2014/KNI#1]
First of all, really nice paper: [An End-to-End Neighborhood-based Interaction Model for
Knowledge-enhanced Recommendation](https://dlp-kdd.github.io/assets/pdf/a8-qu.pdf)!

The paper links to this repo for the code, but it seems empty? Could you maybe point me to the code?

Thanks!!

**Comment by Atomu2014** [comment]
Hi, these days I was preparing to release the paper on arxiv. The code and data will be updated very soon.
